sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - '3'
  - '4'
  - '5'
  - '6'
  - stable
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g grunt-cli
